[package]
name = "api-cli"
version = "0.1.3"
description = "Command line API Client inspired by Bruno"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
repository = "https://github.com/mathieu-lemay/api-cli"
license = "MIT"
edition = "2021"

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
path = "src/main.rs"
name = "api-cli"
test = false

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.7", features = ["derive"] }
clap_complete = "4.5.7"
colored_json = "5.0.0"
dirs = "6.0.0"
env_logger = "0.11.3"
exn = "0.3.0"
handlebars = "6.0.0"
jsonpath-rust = "1.0.4"
log = "0.4.21"
once_cell = "1.19.0"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
# Disabling default features because native-tls uses aws-lc-sys, and that don't build for some reason
reqwest = { version = "0.13.3", default-features = false, features = ["charset", "http2", "system-proxy", "json", "native-tls", "form", "query", "multipart", "stream"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
serde_yaml = "0.9.34"
tabled = { version = "0.20.0", features = ["ansi"] }
textwrap = { version = "0.16.1", features = ["terminal_size"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.9.1", features = ["v4"] }

[dev-dependencies]
rstest = "0.26.0"
serde_urlencoded = "0.7.1"
wiremock = "0.6.0"

[features]
native-tls-vendored = ["reqwest/native-tls-vendored"]
