name: Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Lint
        run: |
          make lint

      - name: Run tests
        run: |
          export CARGO_TERM_VERBOSE=true
          make test
